### ISSUE TITLE
regression in 4.1.1: ${target-base} now an unknown manifest token

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf#23]
This manifest below was created by cf recently, but the latest cf gem 4.1.1 now won't consume it, giving an error `RuntimeError: Unknown symbol in manifest: target-base`

```

---
applications:
- name: name
  memory: 256M
  instances: 1
  url: name.${target-base}
  path: .
```
