### ISSUE TITLE
When cf asks for "Email" it actually expects username

### ISSUE THREAD

**Issue by michaelklishin** [cloudfoundry-attic/cf#52]
When cf asks for "Email" (e.g. if you try to create org without doing `cf login`) it actually expects username: entering an email makes authentication fail, providing my username instead of email makes it succeed.

FTR, here's my SCIM users list from `uaa.yml`:

``` yaml
scim:
  users:
    - marissa|koala|marissa@test.org|Marissa|LastName|uaa.admin
    - michael|michaelpwd|michael@test.org|Michael|LastName|uaa.admin
```
