### ISSUE TITLE
When a manifest file is used the cf command line tool ignores the name specified on the command line

### ISSUE THREAD

**Issue by pradine** [cloudfoundry-attic/cf#70]
When I have a manifest that contains just the environment variables that I want to set as follows:

---

env:
IBM_JVM_LICENSE: L-AWON-8GALN9
IBM_LIBERTY_LICENSE: L-JTHS-95XRL8

The name is ignored when specified on the command line as follows:

C:\temp\liberty\wlp\usr\servers\defaultServer\dropins>cf push snoop --buildpack
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack.git
Could not find snoop' in the manifest.

**Comment by ruthie** [comment]
If you want to push another app with the same code, but with a different name, you can copy the manifest section for your first app and change the name.  For example, a manifest for one of our test apps looks like this:

```
---
applications:
- name: dora
  memory: 256M
  instances: 1
  host: dora
  path: .
```

To use the same code to push another app called dora2 I'd change it to look like this:

```
---
applications:
- name: dora
  memory: 256M
  instances: 1
  host: dora
  path: .

- name: dora2
  memory: 256M
  instances: 1
  host: dora2
  path: .
```

Does that help you do what you're trying to do?

@ruthie @charliebevis
