### ISSUE TITLE
Micro bosh deployment doesn't work for dhcp based networks in Openstack Ice House.

### ISSUE THREAD

**Issue by sudswas** [cloudfoundry-attic/cf#80]
Hi,

I have been trying to deploy micro_bosh using openstack icehouse and dhcp based networks.
Following is the network section of my micro_bosh.yml file:

```
            network:
              type: dynamic
              cloud_properties:
               net_id: <dhcp_net_id_from_neutron>
```

When i execute 

bosh micro deployment micro_bosh

I am getting the following error:

/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize': the scheme https does not accept registry part: :25555 (or bad hostname?) (URI::InvalidURIError)

However this error is not seen when i specify an IP address in the network section like this:

```
            network:
              type: dynamic
              ip: x.y.z.f
              cloud_properties:
               net_id: <dhcp_net_id_from_neutron>
```

I am sure that the DHCP address should not require us to specify an IP address.
